### ISSUE TITLE
Poposisiones

### ISSUE THREAD

**Issue by Mrzx001** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Mrzx001#1]
[Ejercisios preposiciones.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Mrzx001/files/13185880/Ejercisios.preposiciones.pdf)

**Comment by LuisAlexisMorales** [comment]
Portada:2t
Procedimiento:22
Figuras:15
Resultados:22
Total:84.   calificación final:17
Por equipo de: Luis Alexis Morales Jose

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
